name = "marketing-agent-project-tracker"
main = "src/index.js"
compatibility_date = "2026-06-23"
account_id = "651264654473ecfcd0cbaa5b3444a770"

[[d1_databases]]
binding = "DB"
database_name = "marketing-agent-project-tracker"
database_id = "5fbc03d4-2358-4f75-8995-c370dc402374"
